### ISSUE TITLE
Front - Catalogo Usuarios: Evitar que el campo Username acepte espacios (en create y update)

### ISSUE THREAD

**Issue by ombdev** [pianodaemon/alphaville#112]

**Comment by Telematica** [comment]
@ombdev 

Q: ¿Es necesario agregar algún conjunto de caracteres específicos aceptables en el username (?.;_- etc), o sólo con evitar espacios es suficiente?

**Comment by ombdev** [comment]
yo diría que sea simple, solo estos: [a-z][A-Z][0-9]_-
