### ISSUE TITLE
Front: No permitir una Salida a carretera de un vale que no está en el mismo patio que del usuario loggeado.

### ISSUE THREAD

**Issue by ombdev** [pianodaemon/alphaville#123]
Es decir, en pantalla Entradas y Salidas, un vale con estatus ENTRADA o PATIO que además está en un patio diferente al del usuario loggeado, solo deberá llevarlo a la vista del vale y nunca a permitirle hacer la Salida a carretera (forward).

**Comment by Telematica** [comment]
@ombdev 

Q: Esa lógica de no permitir abrir un vale en modo Forward debe aplicar sólo en la pantalla de entradas o salidas, o también cuando intenten ingresar directamente, por ejemplo usando la URL http://18.222.201.4:8080/voucher/421/forward

Si aplica también en el 2do caso, ¿debería hacerles una redirección a /edit o /view, u otra acción?

**Comment by ombdev** [comment]
que redirija a /view en el caso que comentas (y que obviamente tampoco se cumpla lo del patio user == patio vale). En caso de sí cumplirse y también meten el url directo, pues que sí les permita el forward.
