### ISSUE TITLE
Front: Verificar que la conversión de unix time (UTC) a fecha considere el timezone 'America/Mexico_City'

### ISSUE THREAD

**Issue by ombdev** [pianodaemon/alphaville#131]

**Comment by Telematica** [comment]
@ombdev 

¿Podrías por favor especificar el formato de los valores de fechas? 

```
generationTime: 1645317241.8261485
lastTouchTime: 1645317241.8261485
```

Para poder hacer la conversión de manera adecuada mediante Javascript.

**Comment by Telematica** [comment]
Ya hice la verificación y parece que sí se ajusta al timezone local:

Ejemplo: 

```
generationTime: 1645665490.565312
lastTouchTime: 1645665651.9864464
```

![Screen Shot 2022-02-24 at 0 35 51](https://user-images.githubusercontent.com/665162/155471489-23a08859-3a2d-4e58-b145-16ca2f6e9400.png)

![Screen Shot 2022-02-24 at 0 35 41](https://user-images.githubusercontent.com/665162/155471495-3463cabc-34b8-4ecf-89e9-b4b4bfb9147d.png)


`generationTime: 1645665490.565312`
![Screen Shot 2022-02-24 at 0 38 40](https://user-images.githubusercontent.com/665162/155471625-6da542fa-9483-49be-90e9-feb933dff7fa.png)


`lastTouchTime: 1645665651.9864464`
![Screen Shot 2022-02-24 at 0 39 03](https://user-images.githubusercontent.com/665162/155471635-22787fc4-86e8-42e2-9fd2-cb5d11672b7a.png)


@ombdev ¿Podrías confirmarme si tengo que ajustar algo más?

**Comment by pianodaemon** [comment]
Y La tia JUSTA ?
