### ISSUE TITLE
Agregar campo Patio a pantalla catalogo de Usuarios

### ISSUE THREAD

**Issue by ombdev** [pianodaemon/alphaville#134]

**Comment by Telematica** [comment]
Requirement/Story: 
- Agregar campo Patio a pantalla catalogo de Usuarios #134

Acceptance Criteria:

1) Agregar campo al listado de usuarios con la columna "Patio", después de la columna "Apellido"
1.1) Para los usuarios con patioId === 0, agregar leyenda "(Sin patio asignado)" de lo contrario el código del patio
2) Agregar campo al formulario CRUD de usuario
2.1) Validar de forma requerida el campo en toda ocasión (creación y edición)


cc @ombdev > por favor agregar cualquier tarea o criterio de aceptación al issue. Gracias
