### ISSUE TITLE
Use action.payload to keep form data on Saga ERROR actions

### ISSUE THREAD

**Issue by Telematica** [pianodaemon/alphaville#61]
`[CREATE_VOUCHER_ERROR]: (state: any, action: any) => {
    console.log('action: ', action);
    return {
      ...state,
      error: true,
      voucher: action.payload.fields,
      loading: false,
    };
  },`

**Comment by pianodaemon** [comment]
![image](https://user-images.githubusercontent.com/19329780/153080062-5659dde8-6fe1-4703-8d6b-87b91f112e84.png)
