### ISSUE TITLE
Títulos de pantallas para Procesos -> Vales

### ISSUE THREAD

**Issue by ombdev** [pianodaemon/alphaville#79]
Flujo Procesos->Vales:

- Captura de vale. El título de esa pantalla podría cambiarse a '**Entrada de Equipo**'.
- Editar vale. El título cambiaría a '**Entrada de Equipo (edición)**'. Se llega desde el Lapicito en listado (esta parte ya está).
- Visualización de vale. Cambiar título a '**Vale de equipo de amarre**'. Ya están los campos como no editables, lo que también es correcto.

**Comment by Telematica** [comment]
@ombdev 

Podrías confirmarme si estos bullets cubren todos los títulos del header de Vale que actualmente manejamos


- Crear Vale
    Entrada de Equipo

- Modo lectura del Vale (sin importar Estatus)
    Vale de equipo de amarre

- Estatus ENTRADA o PATIO cuando existe y se edita un Vale
    Salida de patio a carretera

- Estatus CARRETERA y se está editando el Vale
    Entrada a patio (edición)

- Default (cualquier otro ESTATUS no considerado, o futuro adicional)
    Entrada a patio

**Comment by ombdev** [comment]
en flujo 2
1) ENTRADA o PATIO -> 'Salida de patio a carretera'
2) CARRETERA -> 'Entrada de carretera a patio'

en flujo 1
1) Boton Agregar vale -> 'Entrada de Equipo'
2) Visualizacion de vale -> 'Vale de equipo de amarre'
3) Lapicito (solo en estatus Entrada de Equipo) -> 'Entrada de Equipo (edición)'
