### ISSUE TITLE
Entrada de carretera a patio: Integrar en front la creación de Incidencias

### ISSUE THREAD

**Issue by ombdev** [pianodaemon/alphaville#83]
Incidences gRPC: Se crearon AlterIncidence, ListIncidences, GetIncidence. De estos el principal es AlterIncidence para que lo integres en la Entrada a patio. Verás atributo 'voucherId', que es la referencia al vale de equipo; 'inspectedBy', que es el usuario que hace la Entrada; 'operator', que es el conductor/operador que está ingresando a patio.

La incidencia surge con estatus 'ABIERTA'.

Como aclaración: los posibles estatus para una incidencia son 'ABIERTA' y 'RESUELTA'.

**Comment by Telematica** [comment]
@ombdev Preguntas respecto a este flujo:

1)
inspectedBy, es el usuario que hace la Entrada : ¿te refieres al usuario que está editando el Vale?
operator :  ¿de dónde saco este valor?

2)
Estatus 'ABIERTA' y 'RESUELTA' ... en el Insomnia el ejemplo de creación viene con status = ACTIVA,  ¿ignoro ese ejemplo?

**Comment by ombdev** [comment]
1. Podría verse como este mapping entre el Vale de equipo y la Incidencia:

(atributo en vale) -> (atributo en incidencia)
deliveredBy -> operator
receivedBy -> inspectedBy

2. Los estatus correctos son los indicados en issues de github. De hecho voy a meter estos estatus tambien en el google docs. Ignora el de Insomnia por favor (lo hice antes de crear el issue).
