### ISSUE TITLE
Usuario asignado a patio: asegurar que no hay hardcode 'NLD'

### ISSUE THREAD

**Issue by ombdev** [pianodaemon/alphaville#84]
Se agregó atributo 'typeCode' al GetPatio rpc. Tendrá el valor 'TRANSFER' cuando se trate de un patio como Nuevo Laredo. La intención de esto es que no se use 'NLD' en hardcode como el patio para la Entrada de equipo/Salida de equipo.

**Comment by Telematica** [comment]
Comentarios respecto a este issue:

Hay tipos de patio:

1. TRANSFER es para hacer entradas y salidas de equipo (configurado en tablas como NLD)
2. COMUN es cualquier otro patio
